name: ssh-pipeline
on:
  push:
    branches:
      - main

env:
  DIR1: "/home/www/BlogUI"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: ssh pipeline 1
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
          DIR2: "/root/lpq"
        with:
          host: ${{ secrets.DR_HOST }}
          user: ${{ secrets.DR_USER }}
          pass: ${{ secrets.DR_PASS }}
          port: ${{ secrets.DR_PORT }}
          connect_timeout: 10s
          script: |-
            cd /home/www
            mkdir test

			
			
			
