name: build and deploy
on: 
  push: 
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install  # 安装依赖
          npm run build  # 执行打包
          tar -zcvf dist.tar.gz dist # 目标文件进行打包
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@master # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个安全拷贝(security copy)操作
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
         host: ${{ secrets.DR_HOST }}
         user: ${{ secrets.DR_USER }}
         pass: ${{ secrets.DR_PASS }}
         port: ${{ secrets.DR_PORT }}
         connect_timeout: 10s
         first_ssh: |
            cd /home/www/BlogUI # 切换到部署目录
            mkdir test
            rm -rf /home/www/BlogUI/dist
            mkdir -p /home/www/BlogUI/dist
         scp: |
           'dist.tar.gz' => /home/www/BlogUI
         last_ssh: |
            cd /home/www/BlogUI # 切换到部署目录
            mkdir test
            tar -zxvf dist.tar.gz  # 将 tar 打包文件进行解压到当前部署目录
