# main.yml
name: deploy to aliyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 使用 node:10
      - name: use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "dist/*"
          REMOTE_HOST: ${{ secrets.DR_HOST }}
          REMOTE_USER: ${{ secrets.DR_USER }}
          TARGET: "/home"
